[theme]
base = "light"
primaryColor = "#6C5CE7"         # accent for buttons & links
backgroundColor = "#FBFBFD"      # soft off-white page bg
secondaryBackgroundColor = "#FFFFFF"
textColor = "#1F2533"
font = "sans serif"

[client]
toolbarMode = "minimal"

[server]
headless = true
enableCORS = false

[browser]
gatherUsageStats = false
